<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="ImranB" failures="1" tests="6" name="com.w2a.API_Batch.testCases.TestCustomerAPI" time="0.023" errors="0" timestamp="2025-02-12T16:32:31 EST" skipped="5">
  <testcase classname="com.w2a.API_Batch.testCases.TestCustomerAPI" name="m1" time="0.012">
    <skipped/>
  </testcase> <!-- m1 -->
  <testcase classname="com.w2a.API_Batch.testCases.TestCustomerAPI" name="m1" time="0.002">
    <skipped/>
  </testcase> <!-- m1 -->
  <testcase classname="com.w2a.API_Batch.testCases.TestCustomerAPI" name="m1" time="0.001">
    <skipped/>
  </testcase> <!-- m1 -->
  <testcase classname="com.w2a.API_Batch.testCases.TestCustomerAPI" name="m1" time="0.005">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at com.w2a.API_Batch.testCases.TestCustomerAPI.m1(TestCustomerAPI.java:31)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- m1 -->
  <testcase classname="com.w2a.API_Batch.testCases.TestCustomerAPI" name="m1" time="0.003">
    <skipped/>
  </testcase> <!-- m1 -->
  <testcase classname="com.w2a.API_Batch.testCases.TestCustomerAPI" name="validateCreateCustomerAPIWithValidData" time="0.000">
    <skipped/>
  </testcase> <!-- validateCreateCustomerAPIWithValidData -->
</testsuite> <!-- com.w2a.API_Batch.testCases.TestCustomerAPI -->
